#!/bin/bash
rm -rf /mnt/stg_w03/var/www/marketplace/frontend/css
rm -rf /mnt/stg_w03/var/www/marketplace/frontend/js
rm  /mnt/stg_w03/var/www/marketplace/frontend/index.html
rm -rf /mnt/stg_w03/var/www/marketplace/frontend/fonts

cp -R dist/{js,css,index.html,fonts} /mnt/stg_w03/var/www/marketplace/frontend/
chmod g+w dist/{js,css,fonts}/* 
chmod g+w dist/index.html 
